# Generated by Django 2.1.2 on 2018-11-14 07:04

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('family_asha', djongo.models.fields.EmbeddedModelField(model_container=api.models.asha, null=True)),
                ('profile', djongo.models.fields.EmbeddedModelField(model_container=api.models.family_profile, null=True)),
                ('amenities', djongo.models.fields.EmbeddedModelField(model_container=api.models.basic_amenities, null=True)),
                ('other', djongo.models.fields.EmbeddedModelField(model_container=api.models.other_service_provision, null=True)),
            ],
        ),
    ]
