# Generated by Django 2.1.2 on 2018-11-30 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asha',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('dispensary', models.CharField(max_length=10)),
                ('anm', models.CharField(max_length=10)),
                ('area_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='basic_amenities',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('house_type', models.CharField(choices=[('1', 'Kaccha'), ('2', 'Pakka'), ('3', 'Semi-Pakka'), ('4', 'Jhuggi'), ('5', 'Homeless')], max_length=1)),
                ('ownership', models.CharField(choices=[('1', 'rented'), ('2', 'own'), ('3', 'government')], max_length=1)),
                ('no_of_rooms', models.IntegerField()),
                ('separate_room', models.BooleanField()),
                ('electricity', models.BooleanField()),
                ('water_source', models.CharField(choices=[('1', 'Govt. tap water'), ('2', 'Hand Pump'), ('3', 'Tanker'), ('4', 'Other')], max_length=1)),
                ('vehicle', models.CharField(choices=[('1', 'two wheeler'), ('2', 'three wheeler'), ('3', 'four wheeler'), ('4', 'none')], max_length=1)),
                ('toilet_facility', models.CharField(choices=[('1', 'own in house'), ('2', 'public'), ('3', 'open defacation')], max_length=1)),
                ('water_available_in_toilet', models.BooleanField()),
                ('drainage', models.CharField(choices=[('1', 'Closed'), ('2', 'Open'), ('3', 'Blocked')], max_length=1)),
                ('garbage_disposal', models.CharField(choices=[('1', 'by sweeper'), ('2', 'open'), ('3', 'other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='family_members',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_of_updation', models.DateField()),
                ('number_of_members', models.IntegerField()),
                ('number_of_males', models.IntegerField()),
                ('number_of_females', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='family_profile',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asha', models.CharField(max_length=50)),
                ('anm', models.CharField(max_length=50)),
                ('health_facility', models.CharField(max_length=100)),
                ('area_code', models.IntegerField()),
                ('area_description', models.TextField()),
                ('date_of_survey', models.DateField(default=django.utils.timezone.now)),
                ('name_head_of_family', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('mobile_no', models.CharField(max_length=10)),
                ('landline', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('1', 'General'), ('2', 'SC'), ('3', 'ST'), ('4', 'Other')], max_length=1)),
                ('religion', models.CharField(choices=[('1', 'Hindu'), ('2', 'Muslim'), ('3', 'Sikh'), ('4', 'Isai'), ('5', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('aadhar_number', models.CharField(blank=True, max_length=16)),
                ('occupation', models.CharField(choices=[('1', 'Private'), ('2', 'Govt'), ('3', 'Self Employed'), ('4', 'Daily Wager'), ('5', 'Unemployed'), ('6', 'Student'), ('7', 'Housewife')], max_length=1)),
                ('marital_status', models.CharField(choices=[('1', 'Married'), ('2', 'Unmarried'), ('3', 'Divorced'), ('4', 'Widowed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='other_service_provision',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('anganwadi_services', models.BooleanField()),
                ('CATs', models.BooleanField()),
                ('Disability', models.BooleanField()),
                ('PDS', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='rntcp',
            fields=[
                ('family_member_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cough', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('fever', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('loss_of_appetite', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('blood_in_sputum', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('chest_pain', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('past_history', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1)),
                ('treatment_status', models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'Left in between'), ('3', 'Not yet started'), ('4', 'Going on')], max_length=1)),
            ],
        ),
    ]
