# Generated by Django 2.1.2 on 2018-10-22 10:01

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('profile', djongo.models.fields.EmbeddedModelField(model_container=api.models.family_profile, null=True)),
                ('amenities', djongo.models.fields.EmbeddedModelField(model_container=api.models.basic_amenities, null=True)),
                ('other', djongo.models.fields.EmbeddedModelField(model_container=api.models.other_service_provision, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='family_profile',
            name='asha',
        ),
        migrations.DeleteModel(
            name='family_profile',
        ),
    ]
